name: tv_show_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
